// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/google/javascript/jscomp/function_info.proto

package com.google.javascript.jscomp;

public final class FunctionInfo {
  static {
    CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.ping();
  }

  private FunctionInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_jscomp_FunctionInformationMap_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jscomp_FunctionInformationMap_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_jscomp_FunctionInformationMap_Entry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jscomp_FunctionInformationMap_Entry_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_jscomp_FunctionInformationMap_Module_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jscomp_FunctionInformationMap_Module_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[1]++;
    java.lang.String[] descriptorData = {
      "\n0com/google/javascript/jscomp/function_" +
      "info.proto\022\006jscomp\"\277\002\n\026FunctionInformati" +
      "onMap\0223\n\005entry\030\001 \003(\n2$.jscomp.FunctionIn" +
      "formationMap.Entry\0225\n\006module\030e \003(\n2%.jsc" +
      "omp.FunctionInformationMap.Module\032\207\001\n\005En" +
      "try\022\n\n\002id\030\002 \002(\005\022\023\n\013source_name\030\003 \002(\t\022\023\n\013" +
      "line_number\030\004 \002(\005\022\023\n\013module_name\030\005 \002(\t\022\014" +
      "\n\004size\030\006 \002(\005\022\014\n\004name\030\007 \002(\t\022\027\n\017compiled_s" +
      "ource\030\010 \002(\t\032/\n\006Module\022\014\n\004name\030f \002(\t\022\027\n\017c" +
      "ompiled_source\030g \002(\tB \n\034com.google.javas",
      "cript.jscompP\001"
    };
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[2]++;
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[3]++;
          internal_static_jscomp_FunctionInformationMap_descriptor =
            getDescriptor().getMessageTypes().get(0);
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[4]++;
          internal_static_jscomp_FunctionInformationMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jscomp_FunctionInformationMap_descriptor,
              new java.lang.String[] { "Entry", "Module", },
              com.google.javascript.jscomp.FunctionInformationMap.class,
              com.google.javascript.jscomp.FunctionInformationMap.Builder.class);
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[5]++;
          internal_static_jscomp_FunctionInformationMap_Entry_descriptor =
            internal_static_jscomp_FunctionInformationMap_descriptor.getNestedTypes().get(0);
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[6]++;
          internal_static_jscomp_FunctionInformationMap_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jscomp_FunctionInformationMap_Entry_descriptor,
              new java.lang.String[] { "Id", "SourceName", "LineNumber", "ModuleName", "Size", "Name", "CompiledSource", },
              com.google.javascript.jscomp.FunctionInformationMap.Entry.class,
              com.google.javascript.jscomp.FunctionInformationMap.Entry.Builder.class);
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[7]++;
          internal_static_jscomp_FunctionInformationMap_Module_descriptor =
            internal_static_jscomp_FunctionInformationMap_descriptor.getNestedTypes().get(1);
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[8]++;
          internal_static_jscomp_FunctionInformationMap_Module_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jscomp_FunctionInformationMap_Module_descriptor,
              new java.lang.String[] { "Name", "CompiledSource", },
              com.google.javascript.jscomp.FunctionInformationMap.Module.class,
              com.google.javascript.jscomp.FunctionInformationMap.Module.Builder.class);
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[9]++;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x.statements[10]++;
  }

  // @@protoc_insertion_point(outer_class_scope)
}

class CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x extends org.codecover.instrumentation.java.measurement.CounterContainer {

  static {
    org.codecover.instrumentation.java.measurement.ProtocolImpl.getInstance(org.codecover.instrumentation.java.measurement.CoverageResultLogFile.getInstance(null), "fc723371-5766-4804-90bc-1687dd8f2639").addObservedContainer(new CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x ());
  }
    public static long[] statements = new long[11];
    public static long[] branches = new long[0];
    public static long[] loops = new long[1];

  public CodeCoverCoverageCounter$38t4zl14dxp4toresdcsmpl9ddm7rg3n6x5ic0x () {
    super("com.google.javascript.jscomp.GEN-SRC-FunctionInfo.java");
  }

  public static void ping() {/* nothing to do*/}

  public void reset() {
      for (int i = 1; i <= 10; i++) {
        statements[i] = 0L;
      }
      for (int i = 1; i <= -1; i++) {
        branches[i] = 0L;
      }
      for (int i = 1; i <= 0; i++) {
        loops[i] = 0L;
      }
  }

  public void serializeAndReset(org.codecover.instrumentation.measurement.CoverageCounterLog log) {
    log.startNamedSection("com.google.javascript.jscomp.GEN-SRC-FunctionInfo.java");
      for (int i = 1; i <= 10; i++) {
        if (statements[i] != 0L) {
          log.passCounter("S" + i, statements[i]);
          statements[i] = 0L;
        }
      }
      for (int i = 1; i <= -1; i++) {
        if (branches[i] != 0L) {
          log.passCounter("B"+ i, branches[i]);
          branches[i] = 0L;
        }
      }
      for (int i = 1; i <= 0; i++) {
        if (loops[i * 3 - 2] != 0L) {
          log.passCounter("L" + i + "-0", loops[i * 3 - 2]);
          loops[i * 3 - 2] = 0L;
        }
        if ( loops[i * 3 - 1] != 0L) {
          log.passCounter("L" + i + "-1", loops[i * 3 - 1]);
          loops[i * 3 - 1] = 0L;
        }
        if ( loops[i * 3] != 0L) {
          log.passCounter("L" + i + "-2", loops[i * 3]);
          loops[i * 3] = 0L;
        }
      }
  }
}

