// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.javascript.jscomp;

public interface FunctionInformationMapOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated group Entry = 1 {
  java.util.List<com.google.javascript.jscomp.FunctionInformationMap.Entry>
      getEntryList();
  com.google.javascript.jscomp.FunctionInformationMap.Entry getEntry(int index);
  int getEntryCount();
  java.util.List<? extends com.google.javascript.jscomp.FunctionInformationMap.EntryOrBuilder>
      getEntryOrBuilderList();
  com.google.javascript.jscomp.FunctionInformationMap.EntryOrBuilder getEntryOrBuilder(
      int index);

  // repeated group Module = 101 {
  java.util.List<com.google.javascript.jscomp.FunctionInformationMap.Module>
      getModuleList();
  com.google.javascript.jscomp.FunctionInformationMap.Module getModule(int index);
  int getModuleCount();
  java.util.List<? extends com.google.javascript.jscomp.FunctionInformationMap.ModuleOrBuilder>
      getModuleOrBuilderList();
  com.google.javascript.jscomp.FunctionInformationMap.ModuleOrBuilder getModuleOrBuilder(
      int index);
}

class CodeCoverCoverageCounter$dn7ge4dckyudb0nrw9pxb81usfshckta5qny93lm0rcjxrzfqn3qbzx11fxaqzacruch extends org.codecover.instrumentation.java.measurement.CounterContainer {

  static {
    org.codecover.instrumentation.java.measurement.ProtocolImpl.getInstance(org.codecover.instrumentation.java.measurement.CoverageResultLogFile.getInstance(null), "fc723371-5766-4804-90bc-1687dd8f2639").addObservedContainer(new CodeCoverCoverageCounter$dn7ge4dckyudb0nrw9pxb81usfshckta5qny93lm0rcjxrzfqn3qbzx11fxaqzacruch ());
  }
    public static long[] statements = new long[0];
    public static long[] branches = new long[0];
    public static long[] loops = new long[1];

  public CodeCoverCoverageCounter$dn7ge4dckyudb0nrw9pxb81usfshckta5qny93lm0rcjxrzfqn3qbzx11fxaqzacruch () {
    super("com.google.javascript.jscomp.GEN-SRC-FunctionInformationMapOrBuilder.java");
  }

  public static void ping() {/* nothing to do*/}

  public void reset() {
      for (int i = 1; i <= -1; i++) {
        statements[i] = 0L;
      }
      for (int i = 1; i <= -1; i++) {
        branches[i] = 0L;
      }
      for (int i = 1; i <= 0; i++) {
        loops[i] = 0L;
      }
  }

  public void serializeAndReset(org.codecover.instrumentation.measurement.CoverageCounterLog log) {
    log.startNamedSection("com.google.javascript.jscomp.GEN-SRC-FunctionInformationMapOrBuilder.java");
      for (int i = 1; i <= -1; i++) {
        if (statements[i] != 0L) {
          log.passCounter("S" + i, statements[i]);
          statements[i] = 0L;
        }
      }
      for (int i = 1; i <= -1; i++) {
        if (branches[i] != 0L) {
          log.passCounter("B"+ i, branches[i]);
          branches[i] = 0L;
        }
      }
      for (int i = 1; i <= 0; i++) {
        if (loops[i * 3 - 2] != 0L) {
          log.passCounter("L" + i + "-0", loops[i * 3 - 2]);
          loops[i * 3 - 2] = 0L;
        }
        if ( loops[i * 3 - 1] != 0L) {
          log.passCounter("L" + i + "-1", loops[i * 3 - 1]);
          loops[i * 3 - 1] = 0L;
        }
        if ( loops[i * 3] != 0L) {
          log.passCounter("L" + i + "-2", loops[i * 3]);
          loops[i * 3] = 0L;
        }
      }
  }
}

