// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/google/javascript/jscomp/instrumentation_template.proto

package com.google.javascript.jscomp;

public final class InstrumentationTemplate {
  static {
    CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5.ping();
  }

  private InstrumentationTemplate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_jscomp_Instrumentation_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jscomp_Instrumentation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5.statements[1]++;
    java.lang.String[] descriptorData = {
      "\n;com/google/javascript/jscomp/instrumen" +
      "tation_template.proto\022\006jscomp\"\231\001\n\017Instru" +
      "mentation\022\026\n\016report_defined\030\001 \001(\t\022\023\n\013rep" +
      "ort_call\030\002 \001(\t\022\023\n\013report_exit\030\006 \001(\t\022\035\n\025d" +
      "eclaration_to_remove\030\003 \003(\t\022\014\n\004init\030\004 \003(\t" +
      "\022\027\n\017app_name_setter\030\005 \001(\tB \n\034com.google." +
      "javascript.jscompP\001"
    };
CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5.statements[2]++;
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5.statements[3]++;
          internal_static_jscomp_Instrumentation_descriptor =
            getDescriptor().getMessageTypes().get(0);
CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5.statements[4]++;
          internal_static_jscomp_Instrumentation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jscomp_Instrumentation_descriptor,
              new java.lang.String[] { "ReportDefined", "ReportCall", "ReportExit", "DeclarationToRemove", "Init", "AppNameSetter", },
              com.google.javascript.jscomp.Instrumentation.class,
              com.google.javascript.jscomp.Instrumentation.Builder.class);
CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5.statements[5]++;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5.statements[6]++;
  }

  // @@protoc_insertion_point(outer_class_scope)
}

class CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5 extends org.codecover.instrumentation.java.measurement.CounterContainer {

  static {
    org.codecover.instrumentation.java.measurement.ProtocolImpl.getInstance(org.codecover.instrumentation.java.measurement.CoverageResultLogFile.getInstance(null), "fc723371-5766-4804-90bc-1687dd8f2639").addObservedContainer(new CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5 ());
  }
    public static long[] statements = new long[7];
    public static long[] branches = new long[0];
    public static long[] loops = new long[1];

  public CodeCoverCoverageCounter$3i6beis0zd4r7z5y1ji34fz8dw1nhezth7fofj045bn6ct4ouiwuzrz5 () {
    super("com.google.javascript.jscomp.GEN-SRC-InstrumentationTemplate.java");
  }

  public static void ping() {/* nothing to do*/}

  public void reset() {
      for (int i = 1; i <= 6; i++) {
        statements[i] = 0L;
      }
      for (int i = 1; i <= -1; i++) {
        branches[i] = 0L;
      }
      for (int i = 1; i <= 0; i++) {
        loops[i] = 0L;
      }
  }

  public void serializeAndReset(org.codecover.instrumentation.measurement.CoverageCounterLog log) {
    log.startNamedSection("com.google.javascript.jscomp.GEN-SRC-InstrumentationTemplate.java");
      for (int i = 1; i <= 6; i++) {
        if (statements[i] != 0L) {
          log.passCounter("S" + i, statements[i]);
          statements[i] = 0L;
        }
      }
      for (int i = 1; i <= -1; i++) {
        if (branches[i] != 0L) {
          log.passCounter("B"+ i, branches[i]);
          branches[i] = 0L;
        }
      }
      for (int i = 1; i <= 0; i++) {
        if (loops[i * 3 - 2] != 0L) {
          log.passCounter("L" + i + "-0", loops[i * 3 - 2]);
          loops[i * 3 - 2] = 0L;
        }
        if ( loops[i * 3 - 1] != 0L) {
          log.passCounter("L" + i + "-1", loops[i * 3 - 1]);
          loops[i * 3 - 1] = 0L;
        }
        if ( loops[i * 3] != 0L) {
          log.passCounter("L" + i + "-2", loops[i * 3]);
          loops[i * 3] = 0L;
        }
      }
  }
}

